### ISSUE TITLE
network_validation-1.0.1.tar.gz missing

### ISSUE THREAD

**Issue by jabelk** [networkop/arista-network-ci#2]
I could not find it on arista.com or through google, only through this:
https://github.com/burnyd/cvp-serverless-openfaas/blob/master/functions/robot/network_validation-1.0.1.tar.gz

**Comment by networkop** [comment]
I know, it's not exactly obvious where it is. 
you need to go to arista.com -> software downloads -> Extensions -> Network Validation.

**Comment by jabelk** [comment]
FYI 
```
Extensions
EOS Extensions and Plugins
```
https://www.arista.com/en/support/software-download

at least for me is not hyperlinked. I have a free account and can download the cEos and vEOS.
